# Generated by Django 4.1.5 on 2023-01-26 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('genre', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=100)),
                ('release_date', models.DateField(verbose_name='Date')),
                ('platform', models.CharField(max_length=100)),
                ('imageURL', models.CharField(max_length=250)),
                ('favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
