# Generated by Django 4.1.5 on 2023-01-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='imageURL',
            field=models.CharField(max_length=500),
        ),
    ]
